apiVersion: v1
kind: Service
metadata:
  labels:
    app: bier-frontend-service
  name: bier-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bier-frontend
