apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bier-ingress
  namespace: dev-bier
  annotations:
    kubernetes.io/ingress.class: extern
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"

spec:
  rules:
  - host: dev.beer.tino.sh
    http:
      paths:
      - backend:
          serviceName: bier-frontend-service
          servicePort: 80

  tls:
  - hosts:
    - dev.beer.tino.sh
    secretName: dev-beer-tino-sh-tls
